### ISSUE TITLE
also remove comments?

### ISSUE THREAD

**Issue by choochootrain** [emumoo/remove-youtube-suggestions#1]
this is a great little extension, thanks for making it!

i added this to also kill comments:
`sheets[0].insertRule("ytd-comments { display: none !important; }");`

i'm happy to make a pull request or whatever if you'd like to include it, otherwise i'll publish a fork so i can have this on all my devices

**Comment by emumoo** [comment]
Now that `checkboxes` are a thing, having an option to remove comments is relatively easy to add, and has been requested multiple times :)
