### ISSUE TITLE
Extension disables "show more replies" in comments?

### ISSUE THREAD

**Issue by Jon-guy30** [emumoo/remove-youtube-suggestions#10]
I seem to have a small problem, in the youtube comments the "show more replies" does not work. When I disable this extension it works again. Like it doesn't even show up. I can't follow threads in youtube.

Is anyone else experiencing this? 

I can provide you with a list of my other extensions to see if there's a possible conflict.

**Comment by emumoo** [comment]
There's a recent feature that removes comments -- probably would've been better to have it default to not remove them -- anyway unchecking the box for `comments` will likely fix this issue. Let me know!

**Comment by Jon-guy30** [comment]
I have the feature disabled already since the update.

**Comment by emumoo** [comment]
Hmm can you give a screenshot of what you mean? I'm not able to recreate it.

A list of other extensions would be great too :)

**Comment by Jon-guy30** [comment]
Sure thing.

![replies](https://user-images.githubusercontent.com/10241225/54474748-83250a80-47e0-11e9-85fc-0d48d9eb8b16.PNG)



![More Replies](https://user-images.githubusercontent.com/10241225/54474751-8d470900-47e0-11e9-8578-f4ec48205286.PNG)


![extensions](https://user-images.githubusercontent.com/10241225/54474993-ec5a4d00-47e3-11e9-82e1-8e87a0e31d94.PNG)


![extensions 2](https://user-images.githubusercontent.com/10241225/54474998-f4b28800-47e3-11e9-87d4-d6fd1dd9d8bc.PNG)


Tbh, this is a minor issue compared to the stupid, and annoying youtube recommendations algorithm. I'm just figuring out what's causing this.

I've made extensive edits to my preferences as well, I'm not sure if that would cause it. I'm sure it's an extension conflict. 

Final comment about UBO, I have all of the filters enabled on it, again, I'm not sure how that would be related.

**Comment by emumoo** [comment]
OK I think I found the issue, should be fixed now (version 3.0.4)

one way to add spaces is with asterisks (3 or more make a horizontal line -- also might need new lines before and after)
```
***
```

***

<img width="66" alt="Screen Shot 2019-03-16 at 3 36 14 PM" src="https://user-images.githubusercontent.com/6572030/54480654-3e5d9b80-4801-11e9-9a36-d9edd76c1043.png">

***

<img width="66" alt="Screen Shot 2019-03-16 at 3 36 14 PM" src="https://user-images.githubusercontent.com/6572030/54480655-41f12280-4801-11e9-9552-b2ecd15b5f13.png">
