### ISSUE TITLE
Homepage suggestions are visible for split second

### ISSUE THREAD

**Issue by whatareyoutalkingaboutyousoundinsane** [emumoo/remove-youtube-suggestions#12]
The normal 'home' page full of suggestions is visible when I go to YouTube.com, for a split second—sometimes for slightly longer than a split second—before the extension kicks in. Is there any way to make it immediate, so they don't flash before getting hidden? (Also is this just me?)

**Comment by ilMagnifico** [comment]
I solved this with uBlock Origin.

**uBlock Origin> Enter element picker mode> select the entire homepage**.

**Comment by Jon-guy30** [comment]
I have this too. Also, sometimes sidebar suggestions appear as well, though it does not disappear again. You have to restart the browser. 

Lately it seems like this extension has become less reliable and not always working. It's not really the extension's fault as much as it is Google's I think. You know how often Google changes YT. The hiding feature does need to become more robust however.

BTW, does anyone else seem to have youtube player controls hidden while watching in full screen? It's very odd.

**Comment by emumoo** [comment]
The delay for removing the homepage suggestions should now be _much_ shorter, as of the most recent update.
