### ISSUE TITLE
Request: Extension for Chrome

### ISSUE THREAD

**Issue by anishmittal2020** [emumoo/remove-youtube-suggestions#15]
Can it be extended to support google chrome?

**Comment by emumoo** [comment]
Hi @anishmittal2020, I believe a comparable extension exists in Chrome. 

With a quick Google, this is the first [result](https://chrome.google.com/webstore/detail/remove-youtube-recommende/khncfooichmfjbepaaaebmommgaepoid?hl=en)

**Comment by anishmittal2020** [comment]
Hi!I knew about it. Its a closed source. Want to use only minimal closed source tools. But now I am using adblocker for this.
