### ISSUE TITLE
Going back a page doesn't load subscriptions

### ISSUE THREAD

**Issue by Mizuki2000** [emumoo/remove-youtube-suggestions#22]
![Screenshot_9](https://user-images.githubusercontent.com/52368799/92316997-45620600-efc1-11ea-939d-5cd9913151c9.jpg)

**Comment by emumoo** [comment]
Ah I hadn't tested with Dark mode enabled. Should be fixed with the latest version (3.2.1). Thanks for bring it to my attention! :)
