### ISSUE TITLE
Not enabled?

### ISSUE THREAD

**Issue by bmitchinson** [emumoo/remove-youtube-suggestions#3]
I've installed the add-on and made sure it's enabled, and upon refreshing the sidebar, suggestions are still present in my video view.

**Comment by emumoo** [comment]
can you send a screen shot?

**Comment by bmitchinson** [comment]
What would you like a screenshot of? Just the youtube page? Or both the on switch and the youtube page?

**Comment by emumoo** [comment]
Both would be great!

**Comment by emumoo** [comment]
@bmitchinson Is this still an issue?

**Comment by bmitchinson** [comment]
Yeah just reinstalled and restarted my browser and still just doesn't work. Everything's as if it wasn't turned on.

**Comment by bmitchinson** [comment]
https://streamable.com/28qcq

Here's a video of nothing being disabled. The icon is present in the search bar, and all options are selected for disabling.

**Comment by bmitchinson** [comment]
https://streamable.com/28qcq

Here's a video of nothing being disabled. The icon is present in the search bar, and all options are selected for disabling.

**Comment by emumoo** [comment]
It looks like you have another Youtube addon enabled, can I ask what it is (they are)? This remove suggestions addon uses css selectors to hide elements from the page. It's possible that the other add on is changing the html which would cause this issue.

**Comment by bmitchinson** [comment]
wow yeah, it was a dark mode theme from some time 2 years ago that I didn't know was still on. Swear I had tried removing it but I guess not!

Thanks for your help! Sorry to have bothered, working splendidly now.

**Comment by emumoo** [comment]
Glad to hear it!
