### ISSUE TITLE
[Request] Extension Toggle in Browser Menu Bar

### ISSUE THREAD

**Issue by bmitchinson** [emumoo/remove-youtube-suggestions#4]
![image](https://user-images.githubusercontent.com/33632286/48216208-a713a380-e349-11e8-9f91-65021bd92e1b.png)
Having a toggle somewhere in the menu bar as pictured above to enable and disable the extension would be nice. I'd like to not have to open my addon settings and change the extension whenever I'm done studying and using youtube for entertainment again.

**Comment by emumoo** [comment]
Good idea! I'll look in to it
