### ISSUE TITLE
turn off autoplay

### ISSUE THREAD

**Issue by foocp** [emumoo/remove-youtube-suggestions#7]
I love it! what's missing, though, is the next logical step: don't automatically go to the next clip.

**Comment by Jon-guy30** [comment]
Hi.

There's an addon that does that already, it's called Stop AutoPlay Next for Youtube by James Fray,

I'm using it and it works as you describe. The author also has a number of other useful addons designed for YouTube.

**Comment by emumoo** [comment]
Jon-guy30 has a good point. In addition to the addon there's a builtin toggle option that will stop "autoplay"

![image](https://user-images.githubusercontent.com/6572030/54248734-2392da80-4514-11e9-9a00-abd74246b974.png)
