### ISSUE TITLE
No videos appearing

### ISSUE THREAD

**Issue by TybaIt** [emumoo/remove-youtube-suggestions#9]
I've used this addon for quite a while and just now all videos disappear when enabling this addon.
No videos are loaded on youtube when searching.

**Comment by tobiolabode** [comment]
I've just found this issue right now, the fix for me is to unblock comments. (untick the comments option from the extension)

**Comment by T-Vos** [comment]
unblocking comments also works for me. thanks!

**Comment by emumoo** [comment]
Just pushed an update that should fix this issue. Thanks for bringing it to my attention and sorry! I should have tested more :)
